# Generated by Django 5.1.3 on 2024-11-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_usermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmodel',
            name='owner',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='place',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
